In [1]:
import numpy as np

1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [359]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [353]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [357]:
np.array([[1, 5, 3, 7, 2],
             [3, 5, 9, 4, 5],
             [2, 4, 8, 7 ,1],
             [6, 7, 5, 1, 2],
             [9, 2, 4, 6, 8]])

array([[1, 5, 3, 7, 2],
       [3, 5, 9, 4, 5],
       [2, 4, 8, 7, 1],
       [6, 7, 5, 1, 2],
       [9, 2, 4, 6, 8]])

4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [355]:
np.random.random((4, 4))

array([[0.6801433 , 0.06388611, 0.05200067, 0.82481388],
       [0.97469736, 0.52860049, 0.93127142, 0.18028382],
       [0.01964597, 0.68483474, 0.92694881, 0.55200071],
       [0.29985147, 0.95631481, 0.68302616, 0.80066104]])

5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [108]:
vector_c = np.array([2, 9, 3, 4, 8])

In [118]:
vector_d = np.array([7, 3, 6, 4, 1])

In [120]:
vector_c + vector_d

array([ 9, 12,  9,  8,  9])

In [122]:
vector_c - vector_d

array([-5,  6, -3,  0,  7])

In [124]:
vector_c * vector_d

array([14, 27, 18, 16,  8])

6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [127]:
vector_e = np.random.randint(1, 11, size=7)

In [427]:
vector_e

array([ 3,  5,  3, 10,  9,  9,  6])

In [129]:
vector_f = np.random.randint(1, 11, size=7)

In [429]:
vector_f

array([ 5,  2,  9, 10, 10,  7,  8])

In [349]:
np.dot(vector_e, vector_f)

353

7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [250]:
matrix_a = np.array([[2, 8],
                    [4, 3]])

In [252]:
matrix_b = np.array([[7, 1, 5],
                    [3, 9, 4]])

In [347]:
np.dot(matrix_a, matrix_b)

array([[38, 74, 42],
       [37, 31, 32]])

8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [258]:
matrix_c = np.array([[4, 5, 1],
                    [2, 9, 7],
                    [6, 3, 8]])

In [345]:
np.linalg.inv(matrix_c)

array([[ 0.17832168, -0.12937063,  0.09090909],
       [ 0.09090909,  0.09090909, -0.09090909],
       [-0.16783217,  0.06293706,  0.09090909]])

9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [443]:
matrix_r = np.random.random((4, 4))

In [445]:
matrix_r

array([[0.61356648, 0.88174851, 0.84702208, 0.30330867],
       [0.25808301, 0.49293717, 0.64154325, 0.25150624],
       [0.75956502, 0.07805566, 0.62888808, 0.3725162 ],
       [0.30044709, 0.41259789, 0.37255048, 0.97905541]])

In [449]:
matrix_r.T

array([[0.61356648, 0.25808301, 0.75956502, 0.30044709],
       [0.88174851, 0.49293717, 0.07805566, 0.41259789],
       [0.84702208, 0.64154325, 0.62888808, 0.37255048],
       [0.30330867, 0.25150624, 0.3725162 , 0.97905541]])

10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [276]:
matrix_d = np.random.randint(1, 10, size=(3, 4))

In [451]:
matrix_d

array([[3, 8, 4, 4],
       [7, 7, 3, 6],
       [9, 1, 2, 2]])

In [278]:
vector_g = np.random.randint(1, 10, size=4)

In [453]:
vector_g

array([9, 8, 4, 7])

In [455]:
np.dot(matrix_d, vector_g)

array([135, 173, 111])

11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [285]:
matrix_e = np.random.random(size=(2,3))

In [457]:
matrix_e

array([[0.84483891, 0.87344267, 0.43885259],
       [0.52854617, 0.91300736, 0.60455368]])

In [287]:
vector_h = np.random.random(3)

In [459]:
vector_h

array([0.06054981, 0.20849802, 0.54542608])

In [339]:
np.dot(matrix_e, vector_h)

array([0.47262755, 0.55210294])

12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [294]:
matrix_f = np.array([[3, 8],
                    [7, 1]])

In [296]:
matrix_g = np.array([[6, 2],
                    [4, 4]])

In [298]:
matrix_f * matrix_g

array([[18, 16],
       [28,  4]])

13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [301]:
matrix_h = np.array([[2, 8],
                    [1, 3]])

In [303]:
matrix_i = np.array([[3, 7],
                    [2, 1]])

In [337]:
np.dot(matrix_h, matrix_i)

array([[22, 22],
       [ 9, 10]])

14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [316]:
matrix_j = np.random.randint(1, 100, size=(5, 5))

In [461]:
matrix_j

array([[92, 80, 90, 35, 60],
       [63, 79, 71, 54, 80],
       [85, 43, 99, 12, 64],
       [97, 13, 19, 67, 14],
       [68, 59, 89, 24, 64]])

In [318]:
matrix_j.sum()

1521

15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [323]:
matrix_k = np.random.randint(1, 10, size=(4, 4))

In [392]:
matrix_k

array([[2, 9, 2, 1],
       [4, 1, 9, 4],
       [4, 1, 9, 2],
       [8, 8, 1, 7]])

In [325]:
matrix_l = np.random.randint(1, 10, size=(4, 4))

In [394]:
matrix_l

array([[2, 7, 9, 4],
       [4, 3, 9, 1],
       [8, 9, 8, 2],
       [4, 2, 3, 6]])

In [329]:
matrix_k - matrix_l

array([[ 0,  2, -7, -3],
       [ 0, -2,  0,  3],
       [-4, -8,  1,  0],
       [ 4,  6, -2,  1]])

16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [362]:
matrix_m = np.random.random(size=(3, 3))

In [368]:
matrix_m

array([[0.67033053, 0.23482073, 0.96325834],
       [0.55274214, 0.07835605, 0.52420164],
       [0.44974294, 0.91816815, 0.97325716]])

In [374]:
vector_sums = matrix_m.sum(axis=1)

In [376]:
vector_sums

array([1.86840961, 1.15529983, 2.34116825])

In [390]:
vector_sums.reshape(3, 1)

array([[1.86840961],
       [1.15529983],
       [2.34116825]])

17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [406]:
matrix_n = np.random.randint(1, 10, size=(3, 4))

In [412]:
matrix_n

array([[4, 4, 1, 3],
       [2, 7, 6, 1],
       [4, 3, 9, 2]])

In [414]:
np.square(matrix_n)

array([[16, 16,  1,  9],
       [ 4, 49, 36,  1],
       [16,  9, 81,  4]])

18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [417]:
matrix_o = np.random.randint(1, 50, size=4)

In [421]:
matrix_o

array([21,  9, 23, 18])

In [419]:
np.sqrt(matrix_o)

array([4.58257569, 3.        , 4.79583152, 4.24264069])