In [1]:
import numpy as np

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1

In [7]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [11]:
arr_b = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [261]:
arr_b.reshape(2, -1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [20]:
arr_c = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
arr_d = np.array([[7, 8, 9], [10, 11, 12]])

In [30]:
np.vstack((arr_c, arr_d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [75]:
arr_e = np.array([1, 2, 3])

In [77]:
repeated_elements = np.repeat(arr_e, 3)

In [87]:
repeated_elements

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [81]:
tiled_elements = np.tile(arr_e, 3)

In [89]:
tiled_elements

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [85]:
np.hstack((repeated_elements, tiled_elements))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [180]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [182]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [101]:
np.array([item for item in np.unique(a) if item in np.unique(b)])

array([2, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [104]:
arr_f = np.random.uniform(1,50, 20)

In [106]:
arr_f

array([36.00933323, 48.76313155, 16.00420901, 27.02802789, 30.82187491,
       12.54801684,  6.81700245, 33.96537894, 19.75645315, 22.77179436,
        6.11687525, 18.50492517, 46.56525291, 36.6140643 , 13.58681331,
       27.41908299, 49.58055462, 34.91579441, 16.85464996, 18.05051376])

In [130]:
arr_sorted = np.sort(arr_f)

In [136]:
arr_sorted

array([ 6.11687525,  6.81700245, 12.54801684, 13.58681331, 16.00420901,
       16.85464996, 18.05051376, 18.50492517, 19.75645315, 22.77179436,
       27.02802789, 27.41908299, 30.82187491, 33.96537894, 34.91579441,
       36.00933323, 36.6140643 , 46.56525291, 48.76313155, 49.58055462])

In [134]:
arr_sorted[-5:]

array([36.00933323, 36.6140643 , 46.56525291, 48.76313155, 49.58055462])

7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [165]:
arr_g = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [167]:
arr_g[~np.isnan(arr_g)]

array([1., 2., 3., 5., 6., 7.])

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [184]:
arr_h = np.array([1,2,3,4,5])
arr_i = np.array([4,5,6,7,8])

In [216]:
arr_j= (arr_h - arr_i)**2

In [220]:
arr_j

array([9, 9, 9, 9, 9])

In [218]:
np.sqrt(sum(arr_j))

6.708203932499369

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [223]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [231]:
count = 0

for i, value in enumerate(x):
    if value == 1:
        count += 1
        if count == 5:
            print(i)       

8


10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [235]:
np.random.seed(100)
arr_k = np.random.randint(0, 5, 10)

In [257]:
arr_k

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [259]:
result = [False] * len(arr_k)
count = {}

for i, value in enumerate(arr_k):
    if value in count:
        count[value] += 1
        if count[value] > 1:
           result[i] = True
    else: count[value] = 1
print(result)

[False, True, False, True, False, False, True, True, True, True]
